
import static javax.swing.JOptionPane.showInputDialog;

/**
 *
 * @author Raquel
 */
public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbRadio = new javax.swing.JLabel();
        jlbCordenaX = new javax.swing.JLabel();
        jlbCordenaY = new javax.swing.JLabel();
        jlbNombreCirculo = new javax.swing.JLabel();
        jlbTCirculo = new javax.swing.JLabel();
        jbtAñadirCirculo = new javax.swing.JButton();
        txtRadio = new javax.swing.JTextField();
        txtCoordenadaEnX = new javax.swing.JTextField();
        txtCoordenadaEnY = new javax.swing.JTextField();
        txtNombreDelCirculo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbVertice1X = new javax.swing.JLabel();
        jlbVertice1Y = new javax.swing.JLabel();
        jlbVertice3X = new javax.swing.JLabel();
        jlbVertice3Y = new javax.swing.JLabel();
        jlbNombreRectangulo = new javax.swing.JLabel();
        txtCoordenada1EnX = new javax.swing.JTextField();
        txtCoordenada1EnY = new javax.swing.JTextField();
        txtCoordenada3EnX = new javax.swing.JTextField();
        txtCoordenada3EnY = new javax.swing.JTextField();
        txtNombreDelRectangulo = new javax.swing.JTextField();
        btnAñadirCuadrado = new javax.swing.JButton();
        jlbTCuadrado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlbMovimientoF = new javax.swing.JLabel();
        jblMoverX = new javax.swing.JLabel();
        jblMoverY = new javax.swing.JLabel();
        txtMoverEnX = new javax.swing.JTextField();
        txtMoverEnY = new javax.swing.JTextField();
        btnMoverFiguras = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtVisualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPresentar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPresentar1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jlbTTriangulo = new javax.swing.JLabel();
        jlbVertic1X = new javax.swing.JLabel();
        jlbVertic1Y = new javax.swing.JLabel();
        jlbVertic2X = new javax.swing.JLabel();
        jlbVertic2Y = new javax.swing.JLabel();
        jlbVertic3X = new javax.swing.JLabel();
        jlbVertic3Y = new javax.swing.JLabel();
        btnAñadirTriangulo = new javax.swing.JButton();
        txtCoordenada1X = new javax.swing.JTextField();
        txtCoordenada1Y = new javax.swing.JTextField();
        txtCoordenada2X = new javax.swing.JTextField();
        txtCoordenada2Y = new javax.swing.JTextField();
        txtCoordenada3X = new javax.swing.JTextField();
        txtCoordenada3Y = new javax.swing.JTextField();
        txtNombreDelTriangulo = new javax.swing.JTextField();
        jlbNombreTriangulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIGURAS GEOMÉTRICAS");
        setBackground(new java.awt.Color(255, 0, 51));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));

        jlbRadio.setText("Radio");

        jlbCordenaX.setText("Coderna x");

        jlbCordenaY.setText("Cordena Y");

        jlbNombreCirculo.setText("Nombre de la figura");

        jlbTCirculo.setText("CIRCULO");

        jbtAñadirCirculo.setText("AGREGAR");
        jbtAñadirCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAñadirCirculoActionPerformed(evt);
            }
        });

        txtRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioActionPerformed(evt);
            }
        });

        txtCoordenadaEnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenadaEnYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCordenaX)
                            .addComponent(jlbCordenaY)
                            .addComponent(jlbNombreCirculo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jlbRadio)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCoordenadaEnX, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCoordenadaEnY, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreDelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jbtAñadirCirculo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jlbTCirculo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlbTCirculo)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRadio)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCordenaX)
                    .addComponent(txtCoordenadaEnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCordenaY)
                    .addComponent(txtCoordenadaEnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombreCirculo)
                    .addComponent(txtNombreDelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtAñadirCirculo)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        jlbVertice1X.setText("Coordenada 1 X");

        jlbVertice1Y.setText("Coordenada 1 y");

        jlbVertice3X.setText("Coordenada 3 X");

        jlbVertice3Y.setText("Coordenada 3 Y");

        jlbNombreRectangulo.setText("Nombre de la figura");

        txtCoordenada3EnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenada3EnXActionPerformed(evt);
            }
        });

        btnAñadirCuadrado.setText("AGREGAR");
        btnAñadirCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirCuadradoActionPerformed(evt);
            }
        });

        jlbTCuadrado.setText("CUADRADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jlbTCuadrado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbVertice1Y)
                            .addComponent(jlbVertice3X)
                            .addComponent(jlbVertice3Y)
                            .addComponent(jlbNombreRectangulo)
                            .addComponent(jlbVertice1X))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCoordenada3EnX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtNombreDelRectangulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCoordenada3EnY, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCoordenada1EnY))
                            .addComponent(txtCoordenada1EnX, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnAñadirCuadrado)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jlbTCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbVertice1X)
                            .addComponent(txtCoordenada1EnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbVertice1Y)
                            .addComponent(txtCoordenada1EnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbVertice3X)
                            .addComponent(txtCoordenada3EnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVertice3Y)
                    .addComponent(txtCoordenada3EnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombreRectangulo)
                    .addComponent(txtNombreDelRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnAñadirCuadrado)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));

        jlbMovimientoF.setText("MOVIMIENTO DE FIGURAS");

        jblMoverX.setText("Moven en X");

        jblMoverY.setText("Mover en Y");

        txtMoverEnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoverEnYActionPerformed(evt);
            }
        });

        btnMoverFiguras.setText("MOVER");
        btnMoverFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverFigurasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnMoverFiguras))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblMoverX)
                            .addComponent(jblMoverY))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMoverEnY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMoverEnX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbMovimientoF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMovimientoF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMoverX)
                    .addComponent(txtMoverEnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMoverY)
                    .addComponent(txtMoverEnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoverFiguras)
                .addGap(21, 21, 21))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));

        jbtVisualizar.setText("VISUALIZAR");
        jbtVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVisualizarActionPerformed(evt);
            }
        });

        txtPresentar.setColumns(20);
        txtPresentar.setRows(5);
        jScrollPane1.setViewportView(txtPresentar);

        txtPresentar1.setColumns(20);
        txtPresentar1.setRows(5);
        jScrollPane2.setViewportView(txtPresentar1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jbtVisualizar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(26, 26, 26))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jlbTTriangulo.setText("TRIANGULO");

        jlbVertic1X.setText("Coordenada 1 X");

        jlbVertic1Y.setText("Coordenada 1 Y");

        jlbVertic2X.setText("Coordenada 2 X");

        jlbVertic2Y.setText("Coordenada 2 Y");

        jlbVertic3X.setText("Coordenada 3 X");

        jlbVertic3Y.setText("Coordenada 3 Y");

        btnAñadirTriangulo.setText("AGREGAR");
        btnAñadirTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTrianguloActionPerformed(evt);
            }
        });

        txtCoordenada1Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenada1YActionPerformed(evt);
            }
        });

        jlbNombreTriangulo.setText("Nombre de la figura");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jlbTTriangulo)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnAñadirTriangulo)
                                .addGap(65, 65, 65))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbVertic2X)
                                            .addComponent(jlbVertic2Y)
                                            .addComponent(jlbVertic3X)
                                            .addComponent(jlbVertic3Y)
                                            .addComponent(jlbVertic1X))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jlbNombreTriangulo)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCoordenada2Y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtCoordenada2X, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCoordenada1X, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCoordenada3X)
                                    .addComponent(txtCoordenada3Y)
                                    .addComponent(txtNombreDelTriangulo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jlbVertic1Y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(txtCoordenada1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlbTTriangulo)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlbVertic1X))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCoordenada1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoordenada1Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbVertic1Y))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoordenada2X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbVertic2X))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoordenada2Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbVertic2Y))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVertic3X)
                    .addComponent(txtCoordenada3X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVertic3Y)
                    .addComponent(txtCoordenada3Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDelTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombreTriangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAñadirTriangulo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCoordenadaEnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenadaEnYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenadaEnYActionPerformed

    private void txtCoordenada3EnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenada3EnXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenada3EnXActionPerformed

    private void btnAñadirCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirCuadradoActionPerformed
        int xr1 = Integer.parseInt(txtCoordenada1EnX.getText());
        int yr1 = Integer.parseInt(txtCoordenada1EnY.getText());
        int xr3 = Integer.parseInt(txtCoordenada3EnX.getText());
        int yr3 = Integer.parseInt(txtCoordenada3EnY.getText());
        Cuadrado rectangulo = new Cuadrado(new Punto(xr1, yr1), new Punto(xr3, yr3));
        rectangulo.nombre = txtNombreDelRectangulo.getText();
        Graficador.agregar(rectangulo);
        this.txtPresentar.append(rectangulo.toString() + "\n");
        txtCoordenada1EnX.setText("");
        txtCoordenada1EnY.setText("");
        txtCoordenada3EnX.setText("");
        txtCoordenada3EnY.setText("");
        txtNombreDelRectangulo.setText("");

    }//GEN-LAST:event_btnAñadirCuadradoActionPerformed

    private void txtMoverEnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoverEnYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoverEnYActionPerformed

    private void jbtAñadirCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAñadirCirculoActionPerformed
        int xc = Integer.parseInt(txtCoordenadaEnX.getText());
        int yc = Integer.parseInt(txtCoordenadaEnY.getText());
        double radio = Double.parseDouble(txtRadio.getText());
        Circulo circulo = new Circulo();
        circulo.radio = radio;
        circulo.centro = new Punto(xc, yc);
        circulo.nombre = txtNombreDelCirculo.getText();
        Graficador.agregar(circulo);
        this.txtPresentar.append(circulo.toString() + "\n");
        txtCoordenadaEnX.setText("");
        txtCoordenadaEnY.setText("");
        txtRadio.setText("");
        txtNombreDelCirculo.setText("");

    }//GEN-LAST:event_jbtAñadirCirculoActionPerformed

    private void btnMoverFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverFigurasActionPerformed
        int dx = Integer.parseInt(txtMoverEnX.getText());
        int dy = Integer.parseInt(txtMoverEnY.getText());
        Graficador.moverFiguras(dx, dy);
        Graficador.grabar();
        txtMoverEnX.setText("");
        txtMoverEnY.setText("");
    }//GEN-LAST:event_btnMoverFigurasActionPerformed

    private void jbtVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVisualizarActionPerformed
        String datos = Graficador.leer();
        this.txtPresentar1.append(datos);
    }//GEN-LAST:event_jbtVisualizarActionPerformed

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadioActionPerformed

    private void btnAñadirTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTrianguloActionPerformed
        int xt1 = Integer.parseInt(txtCoordenada1X.getText());
        int yt1 = Integer.parseInt(txtCoordenada1Y.getText());
        int xt2 = Integer.parseInt(txtCoordenada2X.getText());
        int yt2 = Integer.parseInt(txtCoordenada2Y.getText());
        int xt3 = Integer.parseInt(txtCoordenada3X.getText());
        int yt3 = Integer.parseInt(txtCoordenada3Y.getText());
        Triangulo triangulo = new Triangulo(new Punto(xt1, yt1), new Punto(xt2, yt2), new Punto(xt3, yt3));
        triangulo.nombre = txtNombreDelTriangulo.getText();
        Graficador.agregar(triangulo);
        this.txtPresentar.append(triangulo.toString() + "\n");
        txtCoordenada1X.setText("");
        txtCoordenada1Y.setText("");
        txtCoordenada2X.setText("");
        txtCoordenada2Y.setText("");
        txtCoordenada3X.setText("");
        txtCoordenada3Y.setText("");
        txtNombreDelTriangulo.setText("");
    }//GEN-LAST:event_btnAñadirTrianguloActionPerformed

    private void txtCoordenada1YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenada1YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenada1YActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirCuadrado;
    private javax.swing.JButton btnAñadirTriangulo;
    private javax.swing.JButton btnMoverFiguras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblMoverX;
    private javax.swing.JLabel jblMoverY;
    private javax.swing.JButton jbtAñadirCirculo;
    private javax.swing.JButton jbtVisualizar;
    private javax.swing.JLabel jlbCordenaX;
    private javax.swing.JLabel jlbCordenaY;
    private javax.swing.JLabel jlbMovimientoF;
    private javax.swing.JLabel jlbNombreCirculo;
    private javax.swing.JLabel jlbNombreRectangulo;
    private javax.swing.JLabel jlbNombreTriangulo;
    private javax.swing.JLabel jlbRadio;
    private javax.swing.JLabel jlbTCirculo;
    private javax.swing.JLabel jlbTCuadrado;
    private javax.swing.JLabel jlbTTriangulo;
    private javax.swing.JLabel jlbVertic1X;
    private javax.swing.JLabel jlbVertic1Y;
    private javax.swing.JLabel jlbVertic2X;
    private javax.swing.JLabel jlbVertic2Y;
    private javax.swing.JLabel jlbVertic3X;
    private javax.swing.JLabel jlbVertic3Y;
    private javax.swing.JLabel jlbVertice1X;
    private javax.swing.JLabel jlbVertice1Y;
    private javax.swing.JLabel jlbVertice3X;
    private javax.swing.JLabel jlbVertice3Y;
    private javax.swing.JTextField txtCoordenada1EnX;
    private javax.swing.JTextField txtCoordenada1EnY;
    private javax.swing.JTextField txtCoordenada1X;
    private javax.swing.JTextField txtCoordenada1Y;
    private javax.swing.JTextField txtCoordenada2X;
    private javax.swing.JTextField txtCoordenada2Y;
    private javax.swing.JTextField txtCoordenada3EnX;
    private javax.swing.JTextField txtCoordenada3EnY;
    private javax.swing.JTextField txtCoordenada3X;
    private javax.swing.JTextField txtCoordenada3Y;
    private javax.swing.JTextField txtCoordenadaEnX;
    private javax.swing.JTextField txtCoordenadaEnY;
    private javax.swing.JTextField txtMoverEnX;
    private javax.swing.JTextField txtMoverEnY;
    private javax.swing.JTextField txtNombreDelCirculo;
    private javax.swing.JTextField txtNombreDelRectangulo;
    private javax.swing.JTextField txtNombreDelTriangulo;
    private javax.swing.JTextArea txtPresentar;
    private javax.swing.JTextArea txtPresentar1;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
